# Generated by Django 2.2.14 on 2020-09-26 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0003_normal_ticket_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_ticket_model',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 26)),
        ),
    ]
